baseURL = 'https://hbjnmcd.github.io/portfolio/'
languageCode = 'ru-ru'
title = 'My portfolio || Портфолио'
theme = 'hugo-theme-learn'

 [[menu.shortcuts]] 
    name = "<i class='fab fa-github'></i> Мой Github "
    identifier = "ds"
    url = "https://github.com/hbjnmcd"
    weight = 10

    [[menu.shortcuts]]
    name = "<i class='fas fa-bookmark'></i> Hugo Documentation"
    identifier = "hugodoc"
    url = "https://gohugo.io/"
    weight = 20