baseURL = 'https://hbjnmcd.github.io/portfolio/'
languageCode = 'ru-ru'
title = 'My portfolio'
theme = 'hugo-theme-learn'

[context.production.environment]
  HUGO_BASEURL = "https://learn.netlify.app/"

[params]
  titleSeparator = "|"
  # Позволяет видеть галочки у просмотренных страниц
  showVisitedLinks = true
  #Скрывает поясняющие надписи
  disableShortcutsTitle = true

  disableLandingPageButton = true
  landingPageURL = "/"
  landingPageName = "<i class='fas fa-home'></i> Home"

  themeVariant = "green"

 [[menu.shortcuts]] 
    name = "<i class='fab fa-github'></i> My Github "
    identifier = "ds"
    url = "https://github.com/hbjnmcd"
    weight = 10

    [[menu.shortcuts]]
    name = "<i class='fas fa-bookmark'></i> Hugo Documentation"
    identifier = "hugodoc"
    url = "https://gohugo.io/"
    weight = 20

